Makefile

Add check-env phony target as prerequisite for tools and esp32 targets.
This causes make to bail out immediately if IDF_PATH is unset, preventing
unclear path failure messages during cmake's attempt at adding mbedtls paths based
on this.
Failure after:
```
$ echo $IDF_PATH && make tools
Makefile:99: *** IDF_PATH is not set.  Stop.
$
```
Failure before:
```
$ echo $IDF_PATH && make tools
...
CMake Error at CMakeLists.txt:91 (add_subdirectory):
add_subdirectory given source "/components/mbedtls/mbedtls" which is not an
existing directory.
...
-- Configuring incomplete, errors occurred!
...
make: *** [Makefile:48: build/host/CMakeCache.txt] Error 1
$
```

Expand use of check-env target in Makefile

---

Makefile

From Go 1.16 install subcommand accepts version suffixes and should be used for
executable installation according to [go get deprecation notice](https://go.dev/doc/go-get-install-deprecation)
and [release notes](https://go.dev/doc/go1.16).
Go <1.16 will error out when parsing a version suffix so this adds a check for
Go version and switches the argument and module mode between get and install
accordingly when installing toitpkg.
Shells out with "go version" piped through grep and two additional shell
invocations of bc for integer comparision.
Assumes to have available;
* grep with --perl-regexp for doing look-around (GNU only?)
* echo
* bc
Tested on Ubuntu 20.04 with go 1.13.8.
See also [writeup of module usage across Go versions](https://maelvls.dev/go111module-everywhere/).

Mitigate go 1.13/Ubuntu 20.04 "path@version" syntax error

---

README.md

* add "Build system" section detailing generic build requirements;
* gcc
* golang
* ninja
* cmake
* refer to above section in "Build for Linux"
* use apt instead of apt-get in installation instructions

Elaborate on build requirements

---

Makefile

Use POSIX compliant invocation of [cut](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cut.html) for Go version parsing instead of GNU grep.
Assumes version is the string following the two first characters of the third element of the space delimited set of strings of the one newline delimited line output on stdout by "go version".
* stdout="go version go1.13.8 linux/amd64"
* version="1.13.8"
Fixes #34

Don't use GNU grep for Go detection

---

Makefile

PR for issue #51. Adds `make flash` target. 
`make flash` can be called with ESP32_ENTRY, ESP32_WIFI_PASSWORD, ESP32_WIFI_SSID as with `make esp32` and additionally adds ESP32_PORT, which is required, to specify the port the ESP32 is connected to. 
To compile new changes and flash to device:
`make flash ESP32_PORT=/dev/ttyS17 ESP32_WIFI_PASSWORD=password ESP32_WIFI_SSID=ssid ESP32_ENTRY=examples/hello.toit`
Assumes `python` is installed, IDF_PATH is valid, particular ESP32 can communicate at 921600 baud, and user has permission to access the device (sudo adduser $USER dialout on most systems).

Add make flash target

---

lib/net/impl.toit
lib/net/wifi.toit

We need a cleaner solution that also takes care of the cross process network interface closing (#58).
This unblocks https://github.com/toitlang/jaguar/issues/24.

Workaround issue preventing multiple processes from using net.open.

---

lib/core/utils.toit
lib/net/impl.toit
src/compiler/filesystem_local.cc
src/os_darwin.cc
src/os_linux.cc

This also fixes `filesystem_local.cc` such that we use `USERPROFILE`  env variable instead of  `HOME` on windows.

Renamed platform names and added constants in toit

---

.gitignore
CMakeLists.txt

This means that IDEs (like Kdevelop) can take the cmake-file as input
and understand the code.

Allow cmake to work without extra arguments.

---

tools/toitlsp/cmd/analyze.go
tools/toitlsp/cmd/archive.go
tools/toitlsp/cmd/repro.go
tools/toitlsp/cmd/toitdoc.go
tools/toitlsp/cmd/toitlsp.go
tools/toitlsp/cmd/util.go
tools/toitlsp/go.mod

The toitc executable might be symlinked, so we need to follow it to find
the lib directory.
Also point the SDK to the actual SDK root (which should contain the 'lib' directory).

Follow symlinks when trying to find the SDK root.

---

tools/toitlsp/lsp/compiler/path/path.go

A virtual file is starting with '///'. When converting from compiler
paths to local paths, the language server would convert the slashes to
backslashes thus giving it a new name.
Fixes #183.

Fix LSP server for unsaved files on Windows.

---

CMakeLists.txt

Also don't enable programs and tests for mbedtls.

Make mbedtls compile into `build/host`.

---

src/compiler/compiler.cc
src/compiler/filesystem_local.cc
src/compiler/filesystem_local.h
src/compiler/toitc.cc

This way the vm also localizes its filenames.

Let the compiler localize file paths.

---

.github/workflows/website_dispatch.yml

This will trigger a dispatch event to the toitlang.org repo to rebuild the website when a new release has been created or an existing one was edited.

Trigger dispatch event

---

.github/workflows/ci.yml
CMakeLists.txt
Makefile
README.md
README_OTHERPLATFORMS.md
src/CMakeLists.txt
tools/CMakeLists.txt
tools/toit.cmake

This has the advantage of keeping track of the dependencies.
It also simplifies the Makefile.

Build snapshots in Cmake.

---

src/primitive.h
src/primitive_core.cc
src/resources/pipe.cc
src/resources/tls.cc
src/resources/tls.h

as_cstr relies on the null terminator for on-string
strings and doesn't work for slices.  This change
reduces the use of as_cstr.  Still some uses in
fork and exec.

Reduce use of as_cstr.

---

tests/toit_run_image/CMakeLists.txt

Under windows we can't just prefix the environment options.

Fix way of how environment is passed to command.

---

README.md

Humans have a tendency to stop reading after the first half of a
sentence. Make it clearer that the esp32 tools are only needed when
trying to build an image.

Start the sentence with the 'if'.

---

.gitmodules

The relative path for git submodules is only really convenient when the
repository is private.

Change submodule URL to public repository.

---

src/compiler/resolver.cc
src/compiler/resolver.h
src/compiler/resolver_scope.cc
src/compiler/resolver_scope.h
tests/negative/deprecated_first_segment_test.toit
tests/negative/gold/deprecated_first_segment_test.gold

This removes the deprecation warning and simply uses the last segment.

Remove support for first-segment prefixes.

---

tests/negative/fail.cmake
tests/tools/normalize_gold.cmake

This fixes tests like the following:
```
--- D:/a/toit/toit/build/host/tmp/GOLD_nn7R91SLQEQj	2022-01-10 18:07:25.520160400 +0000
+++ D:/a/toit/toit/build/host/tmp/OUTPUT_nn7R91SLQEQj	2022-01-10 18:07:25.520160400 +0000
@@ -1,7 +1,7 @@
tests\negative\import9_test.toit:3:1: error: Failed to find import '.non_existing'
import .non_existing show A
^~~~~~
-tests\negative\import9_test.toit:3:9: note: Missing library file. Tried 'tests\negative\non_existing.toit' and 'tests\negative\non_existing/non_existing.toit'
+tests\negative\import9_test.toit:3:9: note: Missing library file. Tried 'tests\negative\non_existing.toit' and 'tests\negative\non_existing\non_existing.toit'
import .non_existing show A
^~~~~~~~~~~~
tests\negative\import9_test.toit:10:5: error: Class 'B' does not have any method …
```

Change order in which we localize.

---

src/primitive_core.cc
tests/fail.cmake

The primitive was using `long`, but that's not 64 bits on Windows.
Switched to `word` and `builtin_mul_overflow`.

Fix multiply on win64 architecture.

---

lib/at/session.toit

This makes set work with strings.

Remove data type from AT command

---

src/heap.cc
src/scheduler.cc

Changes the GC logs from:
```
[gc @ 0x3ffc3ad0* | heap: 44kb -> 24kb | external: 0kb -> 0kb | free: 12kb->12kb 2.138ms]
```
to:
```
[gc @ 0x3ffcf9a8* | objects: 28/56K -> 28/28K | overall: 225K/243K@92% -> 225K/243K@92% | free: 4096/18K -> 4096/18K | 2.916ms]
```
to better show the objects (including external stuff before the /), the memory capacity and usage, and the state of the freelists.

Improve GC logs.

---

lib/net/modules/tcp.toit

We used to close without removing the finalizer.

Avoid double close on TCP socket

---

src/objects.h

Don't try to read more from sockets and pipes than
we are told is available.  But do try to read one
byte when we are told 0 are available to trigger the
EWOULDBLOCK error.

Experiment: Can we get rid of Mac LSP hangs?

---

README.md

It's not really used, and we prefer concentrating on one channel.

Remove toit telegram channel from readme.

---

src/objects.cc
src/objects.h
src/program.h
src/third_party/dartino/gc_metadata.h
src/third_party/dartino/mark_sweep.h
src/third_party/dartino/object_memory.cc
src/third_party/dartino/object_memory_copying.cc
src/third_party/dartino/object_memory_mark_sweep.cc

This adds support for some objects that are not
real heap objects, but are placed on the heap to
make it possible to iterate all objects in memory order.
Also renames call sites to roots_do which is the Toit name for
visit_pointers.

Add pseudo-objects that are put on the heap for GC.

---

src/objects.h
src/objects_inline.h
src/third_party/dartino/mark_sweep.h
src/third_party/dartino/object_memory.h
src/third_party/dartino/object_memory_copying.cc
src/third_party/dartino/object_memory_mark_sweep.cc

In Toit we need a reference to the program in order
to determine the size and layout of objects.  Some of
this change is threading that pointer through to the
places that need it.
In the long run we might want to find a way to avoid
this issue - probably the GC will be faster if the
size/layout information is more self-contained in the
heap objects.

Fix many compile errors in new heap.

---

src/CMakeLists.txt
src/third_party/dartino/two_space_heap.h

This class was only used for single-space heaps.
We will be using only two-space generational heaps.

Remove ScavengeVisitor.

---

lib/encoding/url.toit

The whole point of url.encode is that the result is
a normal string, and it's more convenient this way for
concatenating ?-& URLs.

url.encode returns strings.

---

src/resources/tls.cc
tests/tls2_test.toit
tests/tls_test_slow.toit

Also adds clarifying comments to TLS implementation.

Spelling mistake in TLS test error.

---

src/compiler/resolver_method.cc
tests/negative/gold/named_constructor_test.gold
tests/negative/named_constructor_test.toit

We treated `A.foo` as `(A).foo` and complained when `A` didn't have any
unnamed constructor. Now we report that we can't find any 'foo' static
or constructor.

Improve error message for bad static accesses.

---

lib/net/impl.toit
src/primitive.h
src/resources/wifi_esp32.cc

When two processes are trying to connect to the WiFi at the same time,
then the second one falls back to using the System network.
However, at that time the network might not yet be online. We now wait
for it to be online by waiting for the IP-address to be available.
Fixes #570

Allow parallel init of WiFi module.

---

src/heap.cc
src/heap.h
src/memory.h
src/objects.h
src/objects_inline.h
src/printing.cc
src/printing.h
src/process.h
src/third_party/dartino/object_memory.h
src/third_party/dartino/two_space_heap.cc
src/third_party/dartino/two_space_heap.h
src/top.h

This also means their constructors, destructors and
_expand methods are merged.  In this CL we don't reorder
the .h file, so private and public parts are not cleanly
separated.  That will be done in a subsequent moving-only
CL.
Also takes iterate_roots out of the gc() function and
makes it an independent method on ObjectHeap.
Removes Heap::payload_size() which was unused.
Moves NoGC class.

Merge Heap and ObjectHeap classes into one.

---

src/heap.cc
src/heap.h
src/primitive_core.cc
src/primitive_programs_registry.cc
src/process.cc
src/process.h
src/resources/primitive_snapshot.cc
src/scheduler.cc
src/scheduler.h
src/third_party/dartino/object_memory.cc
src/third_party/dartino/object_memory.h
src/third_party/dartino/object_memory_copying.cc
src/third_party/dartino/two_space_heap.cc
src/third_party/dartino/two_space_heap.h

A new heap must immediately have some space to
allocate, since some allocations happen immediately
and can't trigger a GC.
But in Toit any allocation can fail, and that includes the
initial pages for a new heap for a new process.  We handle
this by allocating the first page in the primitive before
trying to create the new process.  This way we can report
back allocation failures to the primitive machinery that
retries the primitive.
This CL extends that logic to the new GC.  In the case of the
new GC we start each two-space heap off with a page per
semispace, which means we will be able to perform a young
space GC.

Allocate initial chunks for new GC heap early.

---

src/CMakeLists.txt
src/heap.h
src/primitive_debug.cc
src/printing.cc
src/third_party/dartino/two_space_heap.h
src/vm.cc

The heap histogram was not implemented for the new heap.
There are two ways to iterate heaps.
1) Using ObjectHeap::Iterator (not implemented for the new heap).
2) Using a visitor object, passed to iterate_objects (not implemented
for the old heap).
We fix this by making a third version that calls one of the others:
3) Passing std::function to a do-like method.

Fix compilation of new-GC.

---

src/heap.cc
src/heap.h
src/messaging.cc
src/objects.cc
src/objects.h
src/primitive_core.cc
src/resources/ble_esp32.cc

Be a bit more defensive about having uninitialized objects on the heap, that can't be traversed.
With a GC stress test that eagerly puts random objects in the old space we would see
junk in arrays allocated by messaging.cc, then abandoned when deserialization was
restarted after an allocation failure.

Don't leave uninitialized objects on the heap

---

src/primitive_esp32.cc
src/utils.h

This change moves the SHA256 state onto the malloc heap,
instead of having it on top of the stack during OTA
commit.

Further reduce the stack size for OTA updates.

---

lib/rmt.toit
src/resources/rmt_esp32.cc

If the RMT ring-buffer has too much data, only copy as much as we
want/can handle. If the user wants to know whether there was more data,
they should just request data with a higher `max_output_len` and
look at the size of the returned bytearray.

Return leading bytes if buffer is too small

---

system/containers.toit

This way one doesn't need to change the printed command line.

Change stacktrace message to have '$SNAPSHOT'.

---

Makefile
src/CMakeLists.txt

Using the environment variable to set an important parameter of the
cmake file doesn't work, as cmake rebuilds itself when it detects that
its files have changed. At that point the environment isn't set and it
would generate cache files with the wrong arguments.

Fix Makefile and Cmake file for image dependencies

---

Makefile

When the cross-compiler isn't found, automatically source export.sh.

Automatically source export.sh

---

tests/tls_test_slow.toit

Disable tsl test.

---

src/third_party/dartino/gc_metadata.h

No discernable performance difference on Linux (if anything a little faster).

Fix data race when marking on two threads at once

---

tests/tls_test_slow.toit

Disable tsl test. (#696)

---

src/third_party/dartino/object_memory.h
src/third_party/dartino/object_memory_copying.cc
src/third_party/dartino/object_memory_mark_sweep.cc
src/third_party/dartino/two_space_heap.cc

This is a Dartino remnant.  We handle this elsewhere in
Toit.

Remove process_weak_pointers().

---

src/os_esp32.cc
src/third_party/dartino/gc_metadata.cc

Also rolls in fix to malloc heap stats.

Roll esp-idf to get heap range directly from malloc.

---

tests/tls_test_slow.toit

The important thing is that wrong sites fail to connect.
By not specifying the exact error message we make the test
less flaky.

tls_test_slow be less picky about the error message

---

lib/monitor.toit

Makes it possible to see whether a latch has already a value.
Also, we now allow to read the value multiple times.

Improve latch

---

src/top.cc

The warning correctly sees that we are using a pointer that might not
exist anymore. But this is just for debugging where we want to see
whether the pointer has changed.

Remove warning in debug mode.

---

src/resources/ble_esp32.cc

When the BLE device is already in use, it used to throw an
OUT_OF_BOUNDS. Now the error is "ALREADY_IN_USE".

Improve BLE error message.

---

src/encoder.cc
src/heap_roots.cc
src/interpreter_core.cc
src/interpreter_run.cc
src/messaging.cc
src/objects.cc
src/objects.h
src/objects_runtime.cc
src/primitive.h
src/primitive_core.cc
src/primitive_debug.cc
src/primitive_font.cc
src/program.h
src/program_heap.cc
src/resources/pipe.cc
src/resources/rmt_esp32.cc
src/resources/tcp_esp32.cc
src/resources/tls.cc
src/resources/udp_bsd.cc
src/resources/udp_esp32.cc
src/resources/udp_linux.cc
src/resources/x509.cc
src/snapshot.cc
src/third_party/dartino/object_memory.cc
src/third_party/dartino/two_space_heap.h
src/visitor.cc

The type tests must not be instance methods, as the compiler is allowed
to assume that instance calls were never done on null-pointers.
If we have a Smi object of value 0, then `o->is_X` lets the compiler
assume that `o` is not equal to `null` (or 0). If we then want to use
`o` as a 0-smi (for example by doing a value check:
`if (Smi::cast(o)->value() == 0)` then the compiler optimizes the check
away as it "knows" that `o` can't be null.

Change `is_type` checks of heap objects.

---

tools/toitlsp/lsp/compiler/multiplex.go

Once there was an issue (like "file already closed"), the server would
go into an infinite loop, wasting CPU.

LSP: Exit loop when there is an error.

---

tests/tls_test_slow.toit

For make glorious stability of test!

Use dkhostmaster.dk instead of oracle.com for TLS test

---

tools/package.lock
tools/package.yaml
tools/stacktrace.toit

This tool (for native stacktraces) now uses host.arguments
to parse command line args.
Also improves it so it can use any elf-compatible objdump if
the Xtensa objdump is not installed.  Demangling may or may
not work in this case.
Faster for the the non-disassembly case where there is no
need to parse millions of lines of disassembly.
By using the new version of pkg-host we detect if objdump
exits with an error without producing meaningful output.

Improve stacktrace.toit.

---

lib/tls/socket.toit
src/compiler/resolver_method.cc
tests/negative/constant_name_test.toit
tests/negative/gold/constant_name_test.gold
tools/mirror.toit

Warn the user when it's likely they forgot a `static`.

Add warning when instance variable resembles constant.

---

src/primitive_core.cc

Because of multithreading we often see another print between the text
and the newline.
This is an attempt to get the newline together with the text more often.

Do print_ in one operation.

---

external/CMakeLists.txt

CMake would complain if it can't find the test we try to mark as
failing. With the new setup it only looks if it a new test is in the
failing-test list.

Make fail-case of external tests more robust.

---

lib/device_impl.toit

The output of the name was a stringified byte-array. For example:
```
#[0x98, 0xcd, 0xac, 0x61, 0x71, 0xcc]
```
Now it either picks the name that got stored with Jaguar, or uses the
hardware ID:
```
96980af0-3b26-59d2-be76-fda35e89df2
```

Try to use the Jaguar device name.

---

Makefile
src/compiler/parser.cc
src/compiler/parser.h
tests/block_test.toit
tests/health/gold/sdk/examples__http__http.toit.gold
tests/negative/gold/no_space_paren_test.gold
tests/negative/no_space_paren_test.toit
third_party/benchmarks/toit/pystone.toit

Often this is an attempt of a C-like call (`foo(x)`).

Warn when a '(' is without space.

---

src/compiler/resolver_method.cc
src/compiler/resolver_method.h
tests/negative/gold/block_call2_test.gold
tests/negative/gold/index_call_test.gold
tests/negative/gold/type9_test.gold
tests/negative/gold/typeB_test.gold
tests/negative/index_call_test.toit

Fixes a confusion in the resolver.
Take the call `o[3] 4`
The parser would correctly parse this as a call of `o[3]` with argument
`4`.
However, the resolver tried to reuse functionality and gave a
call-resolving function just a "target" and "arguments".
For a normal call the "target" was the target of the call (for `foo 1
2`, the `foo` identifier).
For an index call, the "target" was the node itself: `o[3]`.
Once the target and arguments were resolved, the resolver would then
again check whether it was trying to solve a normal call or an index
call. It did this, by looking at the target-node. If it was and
index-node, it assumed that it was resolving and index-call. Otherwise,
it assumed it was for a call-node.
However, this led to the following bug, where a normal node had an
index-call …

Fixes bad resolution of index-calls with parameters

---

.github/workflows/ci.yml

Windows-latest is now Windows-2022.
The fix for mbdetls has been merged. So we don't need an older macos
anymore. See https://github.com/toitlang/toit/issues/130.

Move to newer builder.

---

src/compiler/no_such_method.cc
tests/negative/bad_arguments_super_test.toit
tests/negative/gold/bad_arguments_super_test.gold

When providing helpful error messages of why a method call didn't work,
we didn't take super classes into account.

Fix error message for methods in super classes

---

src/resources/tcp_linux.cc
src/resources/udp_linux.cc

Practically speaking they are nowadays the same error (`#define
EWOULDBLOCK EAGAIN`), but documentation states that they could be
different and should be evaluated both.

Also check for EAGAIN.

---

src/resources/uart_esp32.cc

The race condition has been fixed: https://github.com/espressif/esp-idf/issues/6397

Remove work-around for uart_get_buffered_data_len

---

src/compiler/resolver_method.cc
tests/negative/global_self_ref_test.toit
tests/negative/gold/global_self_ref_test.gold

Add error when a global is initialized using itself

---

lib/gpio/pin.toit

No need to set the interrupt if the pin has already the correct value.

If pin has already value exit wait_for immediately

---

.github/workflows/ci.yml
tests/fail.cmake
tests/image/fail.cmake

Powershell doesn't abort execution when a command fails, so we were not
correctly testing on Windows.

Run tests on windows with bash

---

lib/net/modules/udp.toit
tests/udp_test.toit

When we are stuck in receive and a different task closes our
socket we just want to return null, and not throw an exception.

Cleaner close of UDP socket.

---

src/compiler/resolver_method.cc
tests/negative/constant_name_test.toit
tests/negative/gold/constant_name_test.gold

Otherwise we don't give warnings for `FOO499 ::= 33`.

Allow numbers in constant variable names.

---

src/compiler/resolver_method.cc
tests/health/gold/sdk/tests__lsp__bad_definition_test.toit.gold
tests/negative/constructor_receiver2_test.toit
tests/negative/gold/constructor_receiver2_test.gold
tests/negative/gold/constructor_receiver_test.gold

We now required the constructor to be in parenthesis: `(A).member`.
By removing the deprecated support we can provide better error messages
when the left-hand side points to a constructor.
In the following example we used to give bad messages:
```
class A:
static FOO ::= 499
constructor x:
main:
print A.FOOO
```
```
bad.toit:6:9: error: Argument mismatch for 'A'
Too few arguments provided
print A.FOOO
^
```

Remove support for deprecated A.member.

---

src/compiler/cycle_detector.h

Change was supposed to go with 9d6fe8a1bd872a32db07d26726fdad801a494181
but was accidentally left out.

Remove empty line.

---

src/os.cc
src/top.h

If this doesn't work we may need to reserve the memory
at the start instead of trying to guess where it will
be allocated.

Attempt to work around spurious out-of-memory on M1 Mac.

---

src/os_esp32.cc

Also some formatting improvements, especially when
dumping heap info for individual pages of memory:
* Each page gets its own line drawn box.
* Bignum is renamed to Bignum/TLS.
* We call it "untagged allocations" when we don't know.
* Some ASCII pipes replaced with real line drawing chars.
* Each page has a heading "Page:" to make it clearer.

Fix free memory percent on heap reports with PSRAM.

---

external/CMakeLists.txt
tools/toit.cmake

Hardcode an SDK version number for external package downloads.
The inferred SDK number is lower than the one we need to download all
dependencies in the external packages. As a work-around we hard-code a
version number that works.

Add TPKG_SDK_VERSION for pkg downloads

---

src/os_esp32.cc
src/third_party/dartino/gc_metadata.cc
src/third_party/dartino/object_memory.h
src/third_party/dartino/two_space_heap.cc

The heap iteration can now filter out IRAM so we don't have to filter it out with a hack.

Some small fixes to tracegc and heap accounting

---

src/third_party/dartino/gc_metadata.cc
src/third_party/dartino/gc_metadata.h
src/third_party/dartino/object_memory.cc
src/third_party/dartino/object_memory.h

Restricts the Toit heap to the top half of memory, so that the metadata area can be reduced from 24k to 12k.

Devices with limited memory: reduce heap metadata.

---

src/flash_registry_shared.cc
src/os.h
src/os_esp32.cc
src/os_posix.cc
src/os_win.cc
src/primitive_programs_registry.cc
src/resources/image.cc
tools/firmware.toit

Now communicated through the image info blob, instead of relying on weird link table entries.

Provide the correct address of the programs table

---

lib/gpio/pin.toit
tests/esp32/gpio.toit

It was forgetting to forward the pull_up/pull_down arguments. Also close the pin if the configure fails.

Fix the gpio.Pin constructor.

---

lib/esp32.toit
src/heap_report.cc
system/containers.toit

This report needs a bit more memory, but shows the fragmentation for each 8-byte memory cell.  For it to work we need to output the base64 data in a single line (recognized by Jaguar).

Revive the dump_heap primitive, more detailed malloc report.

---

src/compiler/ir.h
src/compiler/resolver.cc
src/compiler/resolver.h
src/compiler/resolver_method.cc
src/compiler/resolver_method.h
src/compiler/token.h
tests/health/gold/sdk/tests__fuzzer__lib__core__core.toit.gold
tests/negative/future_reserved_test.toit
tests/negative/gold/future_reserved_test.gold

We probably want to make these reserved identifiers.

Reserve 'catch', 'throw', 'rethrow' and 'switch'.

---

lib/net/modules/dns.toit
tests/dns_test.toit

This an initial PR to support IPv6 on the Toit platform. @floitsch @erikcorry

feat(dns): Query AAAA records from DNS resolver

---

lib/crypto/crc.toit
lib/crypto/crc16.toit
lib/crypto/crc32.toit
tests/crc_test.toit

Replaces the nibble-at-a-time CRC32 algorithm with a byte-at-a-time generic algorithm.
Replaces the bit-at-a-time CRC16 algorithm with a byte-at-a-time generic algorithm.

Add generic CRC algorithm

---

src/interpreter.h
src/interpreter_run.cc

The other two methods with the INTERPRETER_CORE (IRAM) attribute are fast_at and compare_numbers.

Move hash_find out of the interpreter itself

---

lib/crypto/aes.toit
tests/crypto_test.toit
tests/crypto_vectors_test.toit

cleartext: Never encrypted.
plaintext: Not encrypted yet/any more (one word).
ciphertext: Encrypted data (one word).

Regularize use of names for (un)encrypted data.

---

src/third_party/dartino/object_memory.cc
src/third_party/dartino/object_memory.h
src/third_party/dartino/object_memory_mark_sweep.cc
src/third_party/dartino/two_space_heap.cc

Previously we fixed pointers in dead new-space objects that seemed to point into old space after compaction. Now we skip those objects.  They will never be touched by the system again:
* The mutator can't reach them.
* Remembered-set object scans only happen in old space.
* Mark stack overflow object scans only look at gray objects.
* Scavenges don't look at dead objects.
* Finalizers only determine that objects are dead, they don't look inside them at their pointers.

GC compaction: Don't fix pointers from dead objects.

---

lib/crypto/aes.toit
src/third_party/dartino/object_memory.h
tests/crypto_vectors_test.toit

It just turns out this is a nicer API when finishing an AesGcm encryption most of the time.

AesGcm: Concatenate the rest of the ciphertext and the tag concatenated.

---

lib/encoding/json.toit
lib/reader.toit
tests/json_test.toit

By using a BufferedReader instead of a plain Reader this means you can stream more than one JSON object from a source.

Allow json.decode_stream to take a BufferedReader.

---

src/os_linux.cc
src/third_party/dartino/gc_metadata.h

This can happen if you exceed 65k mappings on Linux.

Handle failure of mprotect call.

---

external/gold/toit-r46ca01__examples__main.toit.gold
external/gold/toit-r46ca01__tests__test_baudrate_esp32.toit.gold
external/gold/toit-r46ca01__tests__test_esp32.toit.gold
external/gold/toit-tl19a08__examples__main.toit.gold
external/gold/toit-tl19a08__src__tl19a08.toit.gold
external/gold/toit-tl19a08__tests__test_esp32.toit.gold
src/compiler/compiler.cc
tests/lsp/basic_completion_test.toit
tests/lsp/basic_definition_test.toit

We would also like to analyze asserts when compiling, but that's harder to do.

Keep asserts when running the compiler for analysis.

---

lib/core/collections.toit
src/primitive.h
src/primitive_core.cc
tests/array_and_list_test.toit
tests/negative/gold/invalid_program_test.gold

For large sets or maps we build a new index from scratch when we outgrow the old one.  In this case we reuse the arraylets from the old index, rather than creating new arraylets and keeping the old ones alive during rehashing.
This also changes the rules so that we go to LargeArray_ as soon as we exceed the arraylet size.  Previously we stayed at SmallArray_ until we hit the max size for page allocations.  On embedded this will avoid arrays in the 2-3.9k size range, which could waste memory on fragmentation.

When rehashing a Set or Map, reduce the peak memory used.

---

src/compiler/no_such_method.cc
tests/negative/gold/wrong_number_of_arguments_test.gold
tests/negative/wrong_number_of_arguments_test.toit

When the problem is about the wrong number of unnamed args, there's no need to list optional named args to help the user.
Probably want to view this with the ignore-white-space option.

Slightly less verbosity on the no-such-method error.

---

src/encoder.cc
tests/negative/gold/unicode_expect_failure_test.gold
tests/negative/unicode_expect_failure_test.toit

Don't chop up UTF-8 byte sequences in messages

---

examples/http/package.lock
examples/http/package.yaml
src/compiler/parser.cc
tests/health/gold/sdk/examples__http__http.toit.gold
tests/negative/gold/minus_space_test.gold
tests/negative/gold/postfix2_test.gold
tests/negative/minus_space_test.toit
tests/package.lock
tests/package.yaml
third_party/benchmarks/toit/pystone.toit
tools/lsp/server/package.lock
tools/lsp/server/package.yaml
tools/package.lock
tools/package.yaml

This is in preparation for allowing `foo-bar` identifiers.

Add warning when '-' is not surrounded by spaces

---

src/primitive_crypto.cc
src/resources/ble_esp32.cc

Fixing 3 errors in BLE. 
- Init sometimes fails because the sequence of calls were wrong
- Supporting more devices on peripheral would always fail
- Connecting as a central would not wait until MTU was negotiation was complete before allowing service discovery, leading to a timeout
Fixing support for compiling without CRYPTO support.

Fix 3 BLE bugs and enable compilation without CRYPTO

---

Makefile

On Windows the simple comparison didn't work.

Improve check for non-Toitware ESP-IDF fork.

---

lib/system/api/containers.toit
lib/system/containers.toit
src/flash_allocation.h
system/containers.toit
tests/negative/gold/illegal_system_call_test.gold
tools/firmware.toit

It is a little bit inconvenient that the names of dynamically installed container images, do not show up. I'll think about a good way of getting them included, but it is hard to modify the system image assets and there are downsides (mostly size) to encoding the names of the images as assets associated with the individual images.
Jaguar already maintains names for the dynamically installed ones. Not sure if we can use that map somehow or if we need to find a way to provide a name when container images are installed.

Expose names for bundled container images

---

.github/workflows/ci.yml

Some of the builders couldn't start immediately, because we sharded out the normal tests too much. By reducing it a bit, the 'cross' and 'esp32' workflows can now start at the same time as all the other builders.

Use fewer linux builders

---

lib/net/modules/dns.toit
src/compiler/propagation/type_primitive_file.cc
src/primitive.h
src/primitive_file_posix.cc
src/primitive_file_win.cc

On Posix we keep an eye on the /etc/resolv.conf file and
reparse it when it changes to get the currrent name servers.
This is also the way golang does it, and glibc does something
similar.
The reason I made a new primitive is that otherwise we
would end up copying chunks of the file.toit into the core
(currently in pkg-host), which would bloat the VM more on
ESP32 because we can't tree shake based on platform.  Since
the file reading code is in C++ it doesn't affect the size on ESP32
as much.
If we get smarter at tree shaking in a platform-dependent
way we should probably make this more a Toit than C++
implementation and clean it up.
Still to do: Something for ESP32 that sets the default DNS
resolver from the DHCP data.

Use resolv.conf to find name servers on Posix

---

src/primitive.h
src/primitive_file_win.cc
src/resources/pipe_win.cc

Instead of using argv[0] to get the executable.

Use a single macro in the ARGS line of primitives to indicate a Windows path

---

src/embedded_data.cc
src/resources/spi_flash_esp32.cc
src/resources/wifi_esp32.cc
src/top.h

On the ESP32-C3 (risc v5 architecture) the uint32_t and uint32 were not equivalent types in the eyes of the C++ compiler and therefore some virtual functions where not dispatched correctly.
The main change is to shift all the typedef's for ints and uints in top.h to use the stdint versions int8_t, etc.
A few other places had warnings/errors and they have been addressed.

Fixes for esp32c3

---

src/primitive_file_win.cc

The `_wunlink` function fails on read-only files. One has to remove the read-only property first.

On windows, delete read-only files as well.

---

src/compiler/resolver_method.cc
tests/negative/gold/invalid_program_test.gold
tests/negative/gold/string_interpolate2_test.gold
tests/negative/gold/string_interpolate_test.gold
tests/negative/string_interpolate2_test.toit
tests/negative/string_interpolate_test.toit
tests/type_propagation/gold/deltablue_test.gold

When a string interpolation started with the interpolated expression and didn't have any other interpolation we were not checking that the result of calling `stringify` was a string.
We also didn't correctly infer that the type of the expression is a string.

Fix string interpolation type inference.

---

lib/i2s.toit

Removing the check for the restriction on MCLK pin from the toit code. The C++ code does still check it.

The pin restrictions for MCLK is not relevant for ESP32S3.

---

src/resources/uart_esp32.cc
src/resources/uart_esp32_hal.c

Some of the methods called from the ISR was not marked as IRAM. This causes flashing to fail while UART is being used.

Fixing missing IRAM markers

---

src/resources/tls.cc
src/utils.cc
src/utils.h

Now that tagging_mbedtls_calloc tries to GC-then-retry failed allocations, perhaps we don't need to free up memory before doing a handshake.  Lets try this and see how it works.  It's also possible that a less
agressive version of this code would be right.

Don't pre-allocate memory for TLS handshake

---

lib/encoding/json.toit
tests/json_test.toit

It was doing a `catch --trace`, and also had an out-of-bounds access.

Fix streaming json decoder.

---

src/objects.cc
src/program.h

This change was innocent of the crashes we had attributed to it.

Reland stack shrinking during GC (#1518).

---

src/third_party/dartino/gc_metadata.cc

The metadata size adjusts on a sliding scale
according to the size of malloc-able memory.

More fine-grained adjustment of metadata size.

---

Makefile

find toolchains -name sdkconfig -exec rm '{}' ';' when there are no sdkconfig files

fix `make clean` when there are no sdkconfig files

---

src/primitive_crypto.cc
src/siphash.cc

With this change you can disable these TLS encryption protocols in sdkconfig, and the VM will still compile.
Almost all web-accessible servers will work just fine with AES based encryption, so this can save some space.
For desktop/server, the correct place to make this change would be in
third_party/esp_idf/components/mbedtls/mbedtls/include/mbedtls/config.h However, space is not an issue on these platforms.

Make ChaCha20/Poly1305 support optional.

---

src/resources/tls.cc

Low-level error codes are globally unique, but are combined bitwise with
high level errors. This sorts them out when reporting exceptions up to the
Toit code.

Recognize OOM errors from TLS more reliably.

---

Makefile
src/CMakeLists.txt

This is especially useful for cross-compilation.

Add makefile rule for the vessels.

---

Makefile

When compiling for Archlinux we don't need the esptool. Don't create it during installation.

Don't require 'all' for 'install'.

---

tests/esp32/README.md
tests/esp32/rmt.toit
tests/esp32/spi_keep_active.toit

Pin 15 seems to have an internal pull-up resistor which made the open-drain test fail. Switching to a different pin solved this.

Improve esp32 tests.

---

lib/esp32/net/ethernet.toit
lib/net/ethernet.toit
lib/system/api/ethernet.toit

Users of the ethernet can use:
```
import net.ethernet
main:
network := ethernet.open
...
network.close
```
but someone has to provide the ethernet driver as a service by importing `esp32.net.ethernet` and installing a configured `EthernetServiceProvider` instance.

Add ethernet service

---

src/compiler/backend.cc
src/compiler/ir.h
src/compiler/optimizations/utils.cc
src/compiler/optimizations/virtual_call.cc
src/compiler/set.h
src/compiler/tree.cc
tests/equals_test.toit
tests/toitp/tree_shaken2_input.toit
tests/toitp/tree_shaken2_snap_test.toit
tests/toitp/tree_shaken2_toitp_test.toit
tests/toitp/tree_shaken_input.toit
tests/toitp/tree_shaken_snap_test.toit
tests/toitp/tree_shaken_toitp_test.toit

The tree-grower would grow static calls even if they were to instance methods of classes that were not instantiated. These static calls were introduced by an earlier optimization. For example, if there is a static type check before that guarantees (assuming the check works) only one dynamic method can be reached.
Now the grower treats these calls as "filtered" virtual calls. That is, they are selector calls, but if they trigger they can only grow to the target method. As such, they also have to wait for classes to be instantiated before they are added to the grown method set.
Care must be taken with super calls: these are also static calls to instance methods, but we have to handle them as soon as we seen them.
This patch also fixes a bug where a call to `operator ==` was changed into a …

Improve tree shaking and fix optimization bug

---

lib/net/modules/dns.toit

Fall back to the next DNS server if we can connect but get an error after that.
We had a user encountering the following stacktrace:
```
EXCEPTION error.
Connection refused
0: DnsClient.get.<block>.<block> <sdk>/net/modules/dns.toit:218:62
1: DnsClient.get.<block>     <sdk>/net/modules/dns.toit:182:25
2: Task_.with_deadline_.<block> <sdk>/core/task.toit:203:16
3: Task_.with_deadline_      <sdk>/core/task.toit:197:3
4: with_timeout              <sdk>/core/utils.toit:181:24
5: with_timeout              <sdk>/core/utils.toit:164:12
6: DnsClient.get             <sdk>/net/modules/dns.toit:182:5
7: dns_lookup                <sdk>/net/modules/dns.toit:46:17
```
Where the call to `socket.receive` throw the "Connection refused": https://github.com/toitlang/toit/blob/3f93e33624b4fe89433dbabbb56a6cb2 …

Improve DNS fallback.

---

lib/tls/certificate.toit
lib/tls/session.toit
tests/tls_global_cert_test_slow.toit
tests/tls_test_slow.toit

This is a response to the comment on https://github.com/toitware/toit-cert-roots/pull/18
It makes an incompatible change that makes a public method private, but nobody has started using the global trusted roots yet afaik.
An upcoming change to toit-cert-roots will make use of this new type.

Make RootCertificate a real object.

---

examples/espnow.toit
src/resources/espnow.cc
tests/esp32/adc.toit
tests/esp32/espnow1_board1.toit
tests/esp32/espnow1_board2.toit
tests/esp32/espnow1_shared.toit

ESP Now still needs to run without WiFi interfering, but it's now possible to run WiFi programs after the container with ESP Now has finished.

Improve espnow.

---

src/primitive_core.cc

Necessary for `isspace` with certain compilers / libraries.

Add missing include of <ctype.h>

---

lib/net/modules/dns.toit
tests/dns-test.toit

When there are multiple DNS servers available we
were previously unclear about whether they were
there because they knew about different domains,
or whether they were there in case some servers
were unreachable.
We now follow the way Linux does things, and use
them for redundancy, not because they have different DNS databases.  That simplifies things, because we immediately return a negative answer instead of
waiting for DNS servers that may not be available.
Previously we were getting test flakiness if one
server failed to respond for a few seconds. Now
we keep retrying for the full timeout (20s).  With the previous semantics this change would have caused very slow answers in the case where a non-existent domain was looked up and one of the servers was offline.

Robustify DNS lookup.

---

src/third_party/dartino/gc_metadata.cc

This should ensure that different processes are not sharing cache lines when they write to metadata, eg. the remembered set.

Round the offsets of metadata sections to cache line.

---

src/compiler/third_party/libyaml/CMakeLists.txt
src/compiler/third_party/libyaml/README.toitware
src/compiler/third_party/libyaml/toitware2.diff
src/compiler/third_party/semver/CMakeLists.txt

Newer CMake versions complain if the minimum is too low. Just bumping these up was enough.

Update third-parties of compiler.

---

src/third_party/dartino/gc_metadata.cc

For non-SPIRAM ESP32s, this increases the size of the heap metadata from 12k to 16k, but may help for systems that have large Toit heaps and low amounts of malloced memory.

Reduce only-for-malloc area from 160k to 108k

---

src/resources/wifi_esp32.cc

Delay the call to esp_wifi_connect() until we've been told that the WiFi has started.
Remember to call esp_wifi_disconnect() if we're connected when the WiFi is being torn down.

Rework the WiFi start and stop sequences.

---

src/messaging.cc

malloc(0) is implementation dependent and can return a pointer or null. Since we check for 'null' to know whether the malloc failed we are better off not even calling 'malloc(0)'.

Don't malloc(0)

---

src/resources/tls.cc
src/resources/tls.h

We paniced instead of reportint OOM for a malloc
failure at a bad moment.

Fix bug in our TLS socket creation around OOM.

---

src/resources/ble_esp32.cc

When two devices connect, and a one disconnects the advertising stopped. This patch (thanks @mikkeldamsgaard) fixes this.

Fix BLE advertising

---

src/compiler/resolver_method.cc
src/compiler/resolver_method.h
tests/field2-test.toit
tests/negative/final-field4-test.toit
tests/negative/gold/final-field4-test.gold
tests/negative/gold/uninitialized-field-test.gold

Once the 'super' has been called we must not allow changes to final fields.
Fixes https://github.com/toitware/toit/issues/4178

Don't allow mutations of final fields.

---

src/event_sources/epoll_linux.cc
src/primitive_file_win.cc
src/resources/pipe_win.cc

Fix non-blocking on stdio on Windows.
We can't rely on the standard fds being in non-blocking mode on Windows,
so we use a dedicated thread for each of them.

Fix Windows pipes

---

src/compiler/resolver_method.cc
tests/field3-test.toit

After a super call (implicit or not), field accesses now do a dynamic lookup. In that case they might find a getter (or a different field) in a subclass.

Make field lookups dynamic in the instance section

---

src/objects.h
src/objects_runtime.cc
src/primitive.h

When we were converting a COW byte array to a writable byte array in a primitive we didn't notice a heap full error correctly.

Fix failure to recognize an allocation failure.

---

CMakeLists.txt

We weren't using 'sdkVersion' anymore:
https://github.com/toitlang/toit/blob/9da69ab57c3f8496261706921b5881a81cc04770/tools/toitlsp/main.go#L26

Fix version/sdkversion in toitlsp (and thus toitdocs)

---

.github/workflows/ci.yml

Sometimes I push to github just to be able to continue work in another location. I don't necessarily want the CI tests to run, and often I know they will fail.
With this change, the CI doesn't run for git branches named:
erik/wip/foo
erik/wip-foo
wip-foo
wip/foo

Don't run the automated tests on work-in-progress branches.

---

src/compiler/resolver.cc
tests/mixin-interface2-test.toit

We weren't taking mixins into account when checking whether an interface was completely implemented.

Fix interface/mixin checks.

---

src/interpreter.cc
src/os.h
src/os_darwin.cc
src/os_esp32.cc
src/os_linux.cc
src/os_posix.cc
src/os_win.cc
src/primitive_core.cc
src/utils.h

```
┌───────────┬──────────┬─────────────────────────────────────────────────────┐
│   Bytes   │  Count   │  Type                                               │
├───────────┼──────────┼─────────────────────────────────────────────────────┤
│       8   │      1   │  external byte array                                │
│  114688   │     25   │  toit                                               │
│     16384 │        4 │    process   0 931fac5e-1437-8551-7113-3c52f9c9fc95 │
│     12288 │        3 │    process   1 19754d90-0d08-1770-7ef0-c25f0bc5f9b9 │
│     65536 │       16 │    process   2 8be11b04-6d16-e0a3-2da0-dd6d0927e6f3 │
│     16384 │        1 │    GC heap metadata                                 │
│      4096 │        1 │    Spare new-space                                  │
│ …
```

Improve OOM message to include UUID of processes.

---

lib/net/modules/dns.toit

This prevents the DNS code from rejecting replies when running in Google Cloud.

Be more liberal in accepting DNS packets

---

src/compiler/parser.cc
tests/health/gold/sdk/tests__indentation-test.toit.gold
tests/negative/gold/if3-test.gold
tests/negative/gold/indent3-test.gold
tests/negative/if3-test.toit

Warn if 'if' and 'else' are not at same indentation.

---

src/compiler/parser.cc
tests/declaration-test.toit
tests/negative/gold/missing-name-test.gold
tests/syntax-test.toit

This allows us to write something like:
```
foo
foo
bar
--my-named-argument
--other-argument
[and-a-block]
:
body
```

Allow ':' of a method/declaration to be at detent level.

---

tests/lsp/repro-compiler-test-slow.toit
tools/lsp/server/compiler.toit
tools/lsp/server/repro.toit
tools/lsp/server/server.toit
tools/toitlsp/lsp/compiler/compiler.go
tools/toitlsp/lsp/doc_handlers.go
tools/toitlsp/lsp/toit_handlers.go

Eventually we would like to pass project-uris that are depending on the URIs we are working on. This is a first step in that direction. Instead of having the project-URI in the compiler, we pass it for every action.

Give project-uri to compiler actions.

---

lib/core/string.toit

The documentation wasn't shown because it had a new line. I also created a private glob_ so that the named argument isn't visible to users anymore.

Fix 'glob'.

---

tools/toitlsp/cmd/toitdoc.go
tools/toitlsp/lsp/compiler/compiler.go
tools/toitlsp/lsp/doc_handlers.go
tools/toitlsp/lsp/documents.go
tools/toitlsp/lsp/file_system.go
tools/toitlsp/lsp/project_uri.go

Same as #1972, but for the Go version of the LSP.
Instead of having one shared project root, find the project root for each file before running the analysis on it.
Still missing:
- we shouldn't report diagnostics for files that are in different project roots. Otherwise, we could end up with files that have a warning when they are not opened, and then one when they aren't (depending on the project root that is used to analyze them).
- if a summary has changed, then all projects that contain that file should be analyzed again.

Analyze each URI in its own project.

---

tests/lsp/double-import-compiler-test.toit
tools/toitlsp/lsp/doc_handlers.go

This is the Golang port of #1973.
If we have dependent projects, this means that we
currently don't see updates to diagnostics if the file is not sharing the same project root.
We will fix this in the next PR.

Only emit diagnostics for URIs that are in the same project.

---

src/compiler/lock.cc
src/compiler/util.h

On Windows we were joining a local path (`..\foo`) to a filesystem that was using slashes (the LSP filesystem). This lead to the path not being correctly canonicalized.

Fix local/slash confusion on package-path.

---

tools/lsp/server/project-uri.toit
tools/toitlsp/lsp/project_uri.go

If we run `toit.pkg install` inside the .packages directory we now see the installed files.
Pretty much a corner case that shouldn't be super important, but this feels more correct.

Use the last '.packages' as project root.

---

lib/encoding/yaml/encoder.toit
lib/encoding/yaml/parser.toit
tests/yaml-test.toit

The parser was failing on "list-like" elements with the following trace:
```
As check failed: a bool (false) is not a ValueNode_.
0: Parser_.c-l-block-seq-entry <sdk>/encoding/yaml/parser.toit:694:5
1: Parser_.l-plus-block-sequence.<block> <sdk>/encoding/yaml/parser.toit:671:21
2: PegParserBase_.try-parse  <sdk>/encoding/yaml/parser.toit:211:20
3: Parser_.try-parse         <sdk>/encoding/yaml/parser.toit:409:16
...
```

Fix yaml parser.

---

lib/encoding/yaml/parser.toit
tests/yaml-test.toit

Fixed a situation where the automatic value conversion would convert "1.1" to a float and "5" to a int and not keep them as string.

Yaml parse value conversion fix

---

src/toit.cc

'toit' doesn't have a source-path when called with `-s`.

Fix null-pointer exception.

---

tests/strip/throw-test.toit

The throw-test failed on the build-bot.
Adding more debug printing.

Add more debug information.

---

tests/syntax-test.toit

Add an example of 'as', which was broken: https://github.com/toitware/ide-tools/issues/246

Add more syntax.

---

src/compiler/compiler.cc
src/compiler/diagnostic.cc
src/compiler/lsp/completion.cc
src/compiler/lsp/completion.h
src/compiler/lsp/goto_definition.cc
src/compiler/lsp/protocol.cc
src/compiler/lsp/protocol.h
tests/lsp/cancel-compiler-test.toit
tools/lsp/server/compiler.toit
tools/lsp/server/protocol/completion.toit
tools/lsp/server/protocol/document.toit
tools/lsp/server/protocol/initialization.toit
tools/lsp/server/server.toit
tools/toitlsp/go.mod
tools/toitlsp/go.sum
tools/toitlsp/lsp/compiler/compiler.go
tools/toitlsp/lsp/compiler/parser.go
tools/toitlsp/lsp/conn.go
tools/toitlsp/lsp/doc_handlers.go
tools/toitlsp/lsp/handlers.go

Vscode would complete 'foo-' (with completion 'foo-bar') to 'foo-foo-bar'. By adding a range it correctly replaces the prefix.

Add a test-range when a completion prefix ends with '-'

---

src/third_party/dartino/object_memory.cc

This just puts exactly the code that was previously there.
There may be room for improvement.

Replace code accidentally removed from ESP32 mem management

---

tests/strip/as-fail-test.toit

The as-fail-test failed on the buildbot. Add more information to debug what went wrong.

Add debug  information.

---

tests/toitp/summary-toitp-test.toit
tools/toitp.toit

The `--uuid` only prints the UUID, so it can be used in scripts.

Make uuid more prominent in toitp.

---

examples/espnow.toit
lib/esp32/espnow.toit
src/primitive.h
src/resources/espnow_esp32.cc
tests/esp32/espnow1-board1.toit
tests/esp32/espnow1-board2.toit

We were seeing "Peer channel is not equal to the home channel" errors.
Also see https://esp32.com/viewtopic.php?t=18291

Make it easier/possible to change channel for espnow.

---

.github/workflows/ci.yml

The AUR dependency needs the combine step to have uploaded the vessels. Otherwise it can't compute the hashsum of the file.

Fix CI dependency for AUR workflow.

---

lib/io.toit

It was too confusing that it didn't include the first buffered array.

Rename 'processed_' field in Reader.

---

tools/pkg/git/pack.toit

The zlib codec blocks if `write` is used. We need to `try-write` instead.

Fix bad write in pkg manager.

---

CMakeLists.txt

This way we can start to release packages against the new version number and test it with the produced executable (and more importantly the buildbot).

Force the version number.

---

tools/toitlsp/cmd/toitdoc.go
tools/toitlsp/lsp/documents.go

The SDK isn't filtered out in the beginning, but during the export.

Remove misleading code.

---

src/toit.cc
tools/toit.toit

When running the toit snapshot (toit.toit) we want the program path to be set to the executable 'toit'. Otherwise we can't find the bundled programs, like `toit.compile`, `toit.pkg`, etc.
Currently `toit run` shells out to the `toit.run` executable which will set the program-path correctly for the executable it is running. If we optimize this by running directly then we will need to update the program_path.

Fix program-path for 'toit'.

---

lib/encoding/yaml/parser.toit
tests/yaml-test.toit

Yaml currently reserves '@' for beginnings of blocks, as in:
```
foo: @
```
However, we accidentally reserved "Q".
Any block that started with "Q" was marked as invalid. Example:
```
description: Qualification of the author.
```

Fix yaml text starting with "Q".

---

tools/toitlsp/cmd/toitdoc.go
tools/toitlsp/lsp/toitdoc/toitdoc.go

The pkg server (pkg.toit.io) currently sets this information through a header. That's inconvenient and unnecessary.

Store the "mode" (package vs lib) and sdk-path in json.

---

.github/workflows/ci.yml

It's a bit heavy to do them all the time, but just for the releases should be fine.

Run 64-bit debug tests when pushing to master.

---

src/event_sources/ble.h
src/primitive.h
src/resources/ble_darwin.mm
src/resources/ble_esp32.cc
src/tags.h

Don't do reinterpret casts in BLE code.

---

src/objects.h

Old code:
400e7de8 <toit::Object::byte_content(toit::Program*, unsigned char const**, int*, toit::BlobKind) const>: ...
400e7dfc:	ffcb22        	addi	a2, a11, -1
400e7dff:	002222        	l32i	a2, a2, 0
...
400e7e24:	2b3b      	addi.n	a2, a11, 3
400e7e26:	0238      	l32i.n	a3, a2, 0
400e7e28:	0183d6        	bgez	a3, 400e7e44 <toit::Object::byte_content(toit::Program*, unsigned char const**, int*, toit::BlobKind) const+0x5c>
400e7e2b:	2bbb      	addi.n	a2, a11, 11
400e7e2d:	0268      	l32i.n	a6, a2, 0
400e7e2f:	0e2d      	mov.n	a2, a14
400e7e31:	fc5656        	bnez	a6, 400e7dfa <toit::Object::byte_content(toit::Program*, unsigned char const**, int*, toit::BlobKind) const+0x12>
400e7e34:	bb7b      	addi.n	a11, a11, 7
400e7e36:	f27c      	movi.n	a2, -1
400e7e38:	0bb8      	l32i.n	a11, a11, 0 …

Change objects.h to get better code quality on Xtensa.

---

lib/ble.toit
src/compiler/propagation/type_primitive_ble.cc
src/event_sources/ble.h
src/primitive.h
src/resources/ble_darwin.mm
src/resources/ble_esp32.cc
src/tags.h

Instead of using a ResourceGroup for lifetime-management of the BLE we use the adapter instead.
Currently there is a use-after-free if the BLE isn't closed correctly and a remote-device was used. This will be fixed in a follow-up PR.

Introduce BleAdapterResource.

---

lib/ble.toit

The underlying system can't just close services or characteristics. It doesn't make sense to give these 'close' methods to users if it doesn't do anything.

Remove some 'close' methods in the BLE code.

---

lib/ble.toit
src/compiler/propagation/type_primitive_ble.cc
src/primitive.h
src/program.h
src/resources/ble_darwin.mm
src/resources/ble_esp32.cc
tests/esp32/ble1-shared.toit

This also makes it easier to have different callbacks (like for a write-with-response).

Clean up callbacks from NimBLE to Toit.

---

src/resources/ble_esp32.cc

It was taking one too many parameters which made it flaky.

Fix add_characteristic primitive.

---

lib/core/collections.toit
tests/deque-test.toit
tests/type_propagation/gold/deltablue-test.gold
tests/type_propagation/gold/deltablue-test.gold-O2
tests/type_propagation/gold/loop-list-test.gold
tests/type_propagation/gold/loop-list-test.gold-O2

With this change, a Deque is a subclass of the abstract subclass List, which means it has useful methods like []=, index-of, and index-of --binary.
In addition, we add methods remove-at and insert-at, which can be used to insert and remove items from the middle of a list or deque. If the insertion is near the ends of a deque, or near the end of a List_ then the operation is efficient.

Make a Deque a List.

---

src/resources/ethernet_esp32.cc

The eth_w5500_config_t struct is only available if the sdkconfig has support for w5500 enabled.

Don't use w5500 structs if they aren't enabled

---

src/messaging.cc
tests/rpc-test.toit

ListSlice_ can wrap anything that implements List, not just List_.  So we can't assume it's a List_.

Messaging: check the class of the list wrapped by ListSlice_

---

tools/toit.toit

Otherwise we get these messages even when the tools just want to report and error. For example
```
$ toit run tmp/tt.toit
EXCEPTION error.
foo
0: main                      tmp/tt.toit:2:3
EXCEPTION error.
Failed to run toit.run
0: run                       src/toit/tools/toit.toit:484:5
1: compile-or-analyze-or-run src/toit/tools/toit.toit:538:3
2: main.<lambda>             src/toit/tools/toit.toit:98:16
3: Command.run               <pkg:pkg-cli>/cli.toit:186:34
4: main                      src/toit/tools/toit.toit:463:16
```

Don't print error message when 'toit' tools fail.

---

system/extensions/host/run-image-boot-sh.toit
tests/envelope/boot-hello-test.toit

The pushd/popd commands were printing their paths.

Don't emit the test-dir in the boot-output.

---

tests/dns-test.toit
tests/dns-tools-test.toit

After switching toit.io's DNS server some records don't exist anymore.

Update dns tests.

---

tests/envelope/fail.cmake

This test ended up taking more than 5 minutes.

Disable boot-upgrade-test with type propagation

---

tests/toit/assert-test.toit
tools/toit.toit

Partially fixes #2493.
We still need to expose it in Jaguar.

Enable asserts by default for -O0 and -O1 and add flag.

---

lib/encoding/url.toit
tests/encoding-test.toit

This is a breaking change:
- `encode` now always returns a string.
- `decode` always returns a string, and `decode-binary` always returns a ByteArray.

Make url encoding|decoding more predictible.

---

tests/envelope/fail.cmake
tests/pkg/constraint-test.toit
tests/pkg/constraint2-test.toit
tests/pkg/package-test.toit
tests/pkg/registry-test.toit
tests/pkg/semver-test.toit
tests/pkg/setup.toit
tools/pkg/commands/utils_.toit
tools/pkg/constraints.toit
tools/pkg/parsers/semantic-version-parser.toit
tools/pkg/project/lock.toit
tools/pkg/project/package.toit
tools/pkg/registry/cache.toit
tools/pkg/registry/description.toit
tools/pkg/registry/registry.toit
tools/pkg/semantic-version.toit

Just using the given term as prefix doesn't work. For example, 'pkg install foo@1' would match 'v10.0.1'.
Also some refactorings to use conventions that are more in line with the rest of the repository.

Fix install-range constraint.

---

tools/lsp/server/utils.toit

HOME isn't always set on Windows.

Don't use '$HOME' to find the cache directory.

---

src/compiler/ir.h
src/compiler/resolver_method.cc
src/compiler/resolver_method.h
tests/abstract-test.toit
tests/lsp/toitdoc3-compiler-test.toit
tests/negative/comparison-type-test.toit
tests/negative/comparison-type2-test.toit
tests/negative/gold/comparison-type-test.gold
tests/negative/gold/comparison-type2-test.gold
tests/negative/gold/operator-test.gold
tests/negative/gold/static4-test.gold
tests/operators-test.toit
tests/type_propagation/gold/null-equals-test.gold
tests/type_propagation/gold/null-equals-test.gold-O2
tests/type_propagation/null-equals-test.toit

A `x == y` or `foo < bar` is now guaranteed to return a boolean type.

Force comparisons to be boolean.

---

src/compiler/type_check.cc

No need for an extra function.

Simplify type-check code.

---

.github/workflows/ci.yml
tools/snapshot.toit

This fixes the nightly run that runs with `-O2` and `--enable-asserts`.
Also run the slow test only once per night.

Fix assert in snapshot.toit.

---

lib/gpio/gpio.toit

The pin.toit library is moved to its location in a follow-up PR.

Remove the gpio library.

---

tools/toitdoc/src/builder.toit

Without this fix toitdocs state that interfaces implement themselves.

Drop self-interface.

---

tests/CMakeLists.txt

Currently, the nightly buildbot run fails because of a timeout with -O0 (on macos).

Double the timeouts if the optimization override is set.

---

src/aes.h
src/entropy_mixer.h
src/primitive.h
src/primitive_crypto.cc
src/resources/tls.h
src/resources/x509.h
src/sha.h
src/snapshot_bundle.cc

This removes the warnings we get with link-time optimizations.
It's unfortunately also exposing all of the privates of mbedtls.
Ideally we would like to use `private_foo` members, so it's clear where we use non-public functionality. However, we need to import some private headers and these must have `MBEDTLS_ALLOW_PRIVATE_ACCESS` defined, which makes it impossible (or very hard) for us not to set it.
The difference between setting `MBEDTLS_ALLOW_PRIVATE_ACCESS` and not:
Without:
```
typedef struct mbedtls_entropy_context {
mbedtls_md_context_t private_accumulator;
int private_accumulator_started;
int private_source_count;
mbedtls_entropy_source_state private_source[20];
}
mbedtls_entropy_context;
```
With:
```
typedef struct mbedtls_entropy_context {
mbedtls_md_context_t accumulator;
int …
```

Set the MBEDTLS_ALLOW_PRIVATE_ACCESS flag all the time.

---

src/resources/pwm_esp32.cc

The ESP32 worked fine, but other variants use different clock speeds.

Fix PWM for ESP variants.

---

external/CMakeLists.txt

Also don't complain if an external directory doesn't exist. During the first `make enable-external` it's normal that they don't exist.

Add dhtxx to external repos.

---

.github/workflows/ci.yml

On the master, the current workflow is allowed to finish, but intermediate runs might be skipped.
On branches, the latest push cancels existing runs.

Only run one CI per branch.

---

lib/log/log.toit

Usecases:
- Making a new logger or logging related service
that is the same level as the current default
logger.
- Using the level of the default logger to decide
at runtime how to construct logged strings.
eg. If log level is debug or higher, I might
include clickable URLs to further tools or
resources.

Add a getter for the level of a logger.

---

src/resources/spi_flash_esp32.cc

There are still two warnings left, but they are from macros we import.
They might already be fixed on an updated version of the esp-idf.

Fix warnings in spi_flash_esp32.cc

---

external/CMakeLists.txt

They used to get 'toit.run', but nothing outside the Toit repository should use that.

Use 'toit' as argument for external tests.

---

src/resources/gpio_linux.cc

A 'set-pull' would lose the output value of a pin.

Fix gpio on raspberry pi.

---

third_party/libgpiod/LICENSES/GPL-2.0-or-later.txt

The tarball was *sometimes* not extractable on Windows, as the symlink target appeared before the symlink.

Remove symlink from repository.

---

.github/workflows/ci.yml

This makes it possible to use it with the release workflow.

Use TOIT_VERSION instead of event-ref.

---

toolchains/arm.cmake

The cmake CACHE variables are only set the first time, unless there is a `FORCE`.

Fix gnueabi cross compilation.

---

tests/hw/esp-tester/mini-jag.toit
tests/hw/esp32/run-time-test.toit

Turns out the ESP32S3 needs to than 500ms to go through the mini-jag and then start the test.

Fix the runtime test for the ESP32S3.

---

lib/esp32/espnow.toit

The key could already be null, but it was required to provide it.

Make the master key optional for ESP-NOW services.

---

lib/ble/local.toit
src/resources/ble_esp32.cc
tests/hw/esp32/ble7-duplicate-board1.toit
tests/hw/esp32/ble7-duplicate-board2.toit
tests/hw/esp32/ble7-duplicate-shared.toit
tests/hw/esp32/variants.toit

In theory it could be possible to also allow duplicate descriptors under each characteristic, but that's just asking for troubles.
Also make it nicer to add a read-only descriptor (which is the most common one).

Allow multiple services/characteristics with the same uuid.

---

tests/hw/esp32/dht11-board2.toit

The sensor is only updating every 1 (DHT11) or 2 (DHT22) seconds. If we query too fast it doesn't even respond. The driver should handle that.

Add test that we can read the dhtxx without sleeping.

---

lib/core/time.toit
tests/time-test.toit

Allow to parse timestamps without seconds.
