toitlang/toit

- examples/gpio.toit
- examples/i2c.toit
- examples/uart.toit
- lib/at/session.toit
- src/compiler/ar.cc
- src/compiler/ar.h
- src/objects.cc
- src/objects.h
- src/snapshot_bundle.cc
- src/top.h
- tools/snapshot.toit
Includes fix for big strings, and more examples.
> Update to latest version.

- Makefile
- lib/drivers/sequans_cellular.toit
- src/heap.cc
- src/objects.h
- src/primitive_file.cc
This drop includes an improvement to the Makefile.
> Latest version

- examples/deep_sleep.toit
- lib/esp32.toit
- src/primitive.h
- src/primitive_esp32.cc
> Add support for deep sleep on the ESP32.

- Makefile
Generate a snapshot of `tools/snapshot_to_image.toit`.
> Generate snapshot_to_image.snapshot

- CMakeLists.txt
- Makefile
- README.md
- src/CMakeLists.txt
- src/compiler/CMakeLists.txt
- src/compiler/filesystem.cc
- src/compiler/filesystem.h
- src/compiler/filesystem_local.cc
- src/compiler/util.h
Change the compiler to find the lib directory once everything is in an
SDK directory.
> Compile into sdk directory.

- lib/net/impl.toit
> Use 127.0.0.1 as the address of the system network

- tools/image.toit
> Fix image constants.

- README.md
I think it's quite clear that it's open source given the repo.
> Suggestion for README

- src/resources/image.cc
This could provide more insights necessary to address https://github.com/toitlang/jaguar/issues/47.
> Improve checking and exceptions in image writer.

- src/primitive_bitmap.cc
(This is from the QOI branch which I don't plan to land.)
> Make pixmap drawing a little more generic

- lib/esp32.toit
Will add toitdoc comments before submitting.
> Add real-time clock operations on ESP32

- Makefile
> Fix esp32 config dependency.

- tests/project_root_flag/README
- tests/project_root_flag/foo/src/foo.toit
- tests/project_root_flag/lock_dir/package.lock
- tests/project_root_flag/target/src/target.toit
- tests/project_root_flag/target/sub/src/sub.toit
- tests/project_root_flag/test.toit
They don't seem to run at the moment. Needs investigation.
> Add project_root_flag tests.

- toolchains/arm32.cmake
> fixed arm32 warnings by suppressing unnecessary psabi-related changes

- src/toit_esp32.cc
An alternative to https://github.com/toitlang/toit/pull/198 that leaves in the OTA support in case someone needs it.
> Dynamically check for OTA support.

- tools/toitlsp/lsp/compiler/parser.go
This fixes https://github.com/toitlang/toit/issues/252.
> Add newlines for lines read from error message in LSP

- .github/workflows/ci.yml
- tests/CMakeLists.txt
- tests/fail.cmake
- toolchains/host32.cmake
- tools/toitlsp/lsp/conn.go
Mark max_heap_size_test as failing on 32-bit machines.
> Add 32-bit platform.

- lib/reader_writer.toit
- tests/reader_writer_test.toit
> Allow reading from ReaderWriter when there is data.

- src/event_sources/lwip_esp32.cc
> Fix missing , in error_codes.

- CMakeLists.txt
- Makefile
- examples/CMakeLists.txt
- tests/health/CMakeLists.txt
- tests/health/gold/sdk/examples__http__http.toit.gold
- tests/health/gold/sdk/examples__ntp__ntp.toit.gold
- tests/health/gold/sdk/tests__lsp__project_root__.packages__foo__1.0.0__src__foo.toit.gold
- tools/toit.cmake
At the moment we just download the required packages.
> Add support for toit-projects

- src/primitive_file_posix.cc
Also has a fix to hopefully compile for RISCV.
> Roll to esp-idf with better memory accounting.

- lib/core/numbers.toit
- lib/core/utils.toit
- lib/encoding/url.toit
- lib/uuid.toit
- tests/encoding_test.toit
- tests/uuid_test.toit
Also adds 3 functions to the global namespace of utils.toit - I could make them private?
> Add url.decode to match url.encode

- lib/device.toit
Values are encoded as UBJSON.
Fixes #420.
> Documentation on what a flash-store value can be.

- src/CMakeLists.txt
- src/interpreter.cc
- src/interpreter.h
- src/interpreter_core.cc
- src/interpreter_run.cc
- src/primitive_core.cc
Improves performance of Richards on ESP32 by 15%.
> Refactor interpreter

- src/third_party/dartino/object_memory.cc
- src/third_party/dartino/object_memory.h
Changing object layout during program run is not something we do.
> Remove Dartino code related to schema change

- src/objects.cc
- src/objects.h
- src/program.h
- src/third_party/dartino/mark_sweep.h
- src/third_party/dartino/object_memory_mark_sweep.cc
We have too many things called chunks in our system.
The Dartino GC adds two more.  Reduce that to one.
> Rename FreeListChunk to FreeListRegion.

- src/third_party/dartino/two_space_heap.cc
- src/third_party/dartino/two_space_heap.h
Unedited.  These were called heap.h and heap.cc in Dartino.
> Add two_space_heap.cc and two_space_heap.h from Dartino.

- src/third_party/dartino/object_memory.cc
- src/third_party/dartino/object_memory.h
- src/third_party/dartino/object_memory_copying.cc
- src/third_party/dartino/object_memory_mark_sweep.cc
- src/third_party/dartino/two_space_heap.cc
- src/third_party/dartino/two_space_heap.h
Finalizers are rather different in Toit, so this code
is not useful.
> Remove weak pointer handling from Dartino heap.

- src/messaging.cc
- src/messaging.h
- tests/ctest/external_messaging_test.cc
Not sure if this is the most useful API, but now it is consistent.
> Always free sent external message payloads

- src/objects.cc
As far as I can tell, all uses of ByteArray are
OK with a zero length external byte array that
has a null external data address.
> Fix ByteArray resize to zero size.

- .github/workflows/ci.yml
This reverts commit 091212a39de82e5a814601525e61e63eb0cea2e2.
> Revert "Allow CI to run on workflow dispatch. (#545)"

- src/compiler/filesystem_local_win.cc
This might also work for network drives.
> Treat WSL paths as absolute.

- src/flags.h
- src/heap.cc
- src/memory.cc
- src/scheduler.cc
- src/scheduler.h
- src/third_party/dartino/mark_sweep.h
- src/third_party/dartino/object_memory.h
- src/third_party/dartino/object_memory_mark_sweep.cc
- src/third_party/dartino/two_space_heap.cc
- src/third_party/dartino/two_space_heap.h
This is just a small adapter class.
Also a bunch of compile fixes for the new GC - still doesn't
link.
> Bring over HeapObjectPointerVisitor from Dartino.

- src/compiler/resolver_method.cc
- tests/negative/gold/incomplete_static_access_test.gold
- tests/negative/incomplete_static_access_test.toit
This error only triggered in debug mode.
> Fix invalid symbol access in the compiler

- lib/rmt.toit
- src/primitive.h
- src/resources/rmt_esp32.cc
And fix various spelling issues.
> Rename transfer -> transmit in RMT

- src/heap.cc
- src/third_party/dartino/object_memory.h
- src/third_party/dartino/object_memory_copying.cc
- tests/ctest/fail.cmake
> Fix external processes for new GC

- lib/gpio/pwm.toit
- src/primitive.h
- src/resources/pwm_esp32.cc
> Add support for changing the frequency of the PWM.

- lib/rmt.toit
- tests/rmt_signals_test.toit
Also change the order of the arguments to the `Signal.do` block.
> Rename 'signal_X' to just 'X'.

- src/third_party/dartino/object_memory_mark_sweep.cc
When the heap reaches a certain size we start allocating larger
chunks for efficiency.  If that fails we should fall back to
one-page chunks on embedded.
> Fall back to smaller size when multipage chunk fails

- src/third_party/dartino/mark_sweep.h
- src/third_party/dartino/object_memory_mark_sweep.cc
- src/third_party/dartino/two_space_heap.cc
This was used for stack handling in Dartino.
> Remove unused set_source_address.

- src/third_party/dartino/object_memory_mark_sweep.cc
- src/utils.cc
- src/utils.h
popcount is used in compact and sweep.  This speeds up compact by about 10%.
I also tried terminating the loop early if u was zero, but that was slower than this.
> Xtensa does not have popcount, this is faster

- .github/workflows/ci.yml
No need to run 32bits and debug separately.
> Run debug tests in 32bits.

- lib/net/modules/dns.toit
> Expose create_query from dns.toit

- lib/spi.toit
- src/primitive.h
- src/resources/spi_esp32.cc
- tests/esp32/spi_keep_active.toit
> Add a way to keep CS active.

- external/gold/mcp2518fd-driver__example__spi.toit.gold
- external/gold/mcp2518fd-driver__src__driver.toit.gold
- external/gold/mcp2518fd-driver__src__mcp2518fd.toit.gold
- external/gold/toit-color-tft__examples__get_display.toit.gold
- external/gold/toit-color-tft__examples__tft_demo.toit.gold
- external/gold/toit-color-tft__examples__watch_demo.toit.gold
- external/gold/toit-color-tft__src__color_tft.toit.gold
- external/gold/toit-hx711__examples__print_measurements.toit.gold
- external/gold/toit-hx711__src__hx711.toit.gold
- external/gold/toit-m5stack-core2__examples__i2c_scan.toit.gold
- external/gold/toit-m5stack-core2__examples__main.toit.gold
- external/gold/toit-m5stack-core2__examples__tft_demo.toit.gold
- external/gold/toit-m5stack-core2__examples__touch.toit.gold
- external/gold/toit-m5stack-core2__src__m5stack_core2.toit.gold
- external/gold/toit-tm1640__examples__alphabet.toit.gold
- external/gold/toit-tm1640__examples__clock.toit.gold
- external/gold/toit-tm1640__examples__scroll.toit.gold
- external/gold/toit-tm1640__src__tm1640.toit.gold
- lib/gpio/pin.toit
- lib/spi.toit
- tests/esp32/gpio.toit
Also rename from `config` to `configure`.
> Improve configuration of pins.

- .github/workflows/ci.yml
The github cache was not having the permissions to access the apt
packages.
> Fix apt-cacher-ng.

- tools/tpkg/go.mod
- tools/tpkg/go.sum
This update fixes the environment entry in the package.yaml file.
> Update tpkg dependency.

- .github/workflows/ci.yml
The old 18.04 system is deprecated.
> Switch to more recent ubuntu.

- src/CMakeLists.txt
- src/compiler/executable.cc
Also unsign vessels. They should not be run.
> Fix vessels on M1.

- lib/system/api/containers.toit
- lib/system/containers.toit
- system/boot.toit
- system/containers.toit
- system/flash/image_writer.toit
- tests/negative/gold/illegal_system_call_test.gold
- tools/image.toit
- tools/toit.run.toit
This will be controllable through `jag run -D run.boot ...`.
> Add run flags to ContainerImageWriter.commit

- external/CMakeLists.txt
- tools/toit.cmake
This reverts commit 65b1fcdc7d11fb5ab829c7dd53c84050e323e782.
> Revert "Add TPKG_SDK_VERSION for pkg downloads (#1010)"

- lib/uart.toit
- src/primitive.h
- src/resources/uart_esp32.cc
- src/resources/uart_posix.cc
Support for UART on Darwin and for reading and writing control lines
> Add UART support for darwin and added control of RTS/DTR

- lib/gpio/pin.toit
- tests/esp32/wait_for1.toit
- tests/esp32/wait_for2.toit
> Fix race condition in 'Pin.wait_for'.

- lib/gpio/pin.toit
- tests/esp32/wait_for1.toit
- tests/esp32/wait_for2.toit
The wait_for sometimes wakes up even though the pin isn't set yet. Simply go back to wait for the state change.
> Fix pin.wait_for.

- lib/ble.toit
- lib/encoding/json.toit
- tests/json_test.toit
This way we can escape individual strings without
pulling in the whole JSON library.
> Unentangle JSON string escaping from general JSON encoding.

- lib/ble.toit
- src/resources/ble_esp32.cc
Fixing some omissions from the ble rewrite.
> Fixes for ble descriptor

- lib/core/collections.toit
We want searches for "stack" or "queue" to find the deque class.
> Improve documentation of deque.

- .github/workflows/ci.yml
This is the last version that runs on Windows 7.
> Use Python 3.8.

- src/resources/i2c_esp32.cc
- src/resources/pulse_counter_esp32.cc
- src/resources/pwm_esp32.cc
- src/resources/rmt_esp32.cc
We were missing some units due to an undefined precompiler variable.
> Fix pulse counter test.

- lib/bignum.toit
- src/resources/tls.cc
- tests/bignum_test.toit
Also rename Bignum constructor to `hex` instead of unnamed.
> Fix issue with equality between int and Bignum.

- Makefile
> Change 'host' to '$(HOST)' in Makefile.

- lib/net/wifi.toit
> Fix signal-strength in wifi.

- README.md
The added instructions made it possible to get compiling on a virtual-box image provided by Microsoft.
> Add more instructions for Windows.

- src/compiler/compiler.cc
- src/compiler/filesystem.cc
- src/compiler/filesystem.h
- src/compiler/filesystem_archive.h
- src/compiler/filesystem_hybrid.cc
- src/compiler/filesystem_hybrid.h
- src/compiler/filesystem_local.h
- src/compiler/filesystem_local_posix.cc
- src/compiler/filesystem_local_win.cc
- src/compiler/filesystem_lsp.h
- src/compiler/lock.cc
On Windows a relative path can be either relative to the current working directory (or another file), or relative to the drive.
> Introduce relative_anchor function.

- tools/firmware.toit
It is legal to use '/' as well.
> Don't assume that separators are '\' on Windows.

- src/resources/espnow.cc
It's almost never the correct approach to reboot if something doesn't go right. Many of the cases in the espnow library can be influenced by the user and should thus give an error message.
> Don't use 'FATAL_IF_NOT_ESP_OK' in espnow code

- src/resources/gpio_esp32.cc
Also make the counter variable static (to the file).
> Don't use IRAM_ATTR on variables.

- lib/system/services.toit
- tests/negative/gold/illegal_system_call_test.gold
This reverts commit a59e88e11528fb11f96c4dd12e43a08d61696c53.
> Revert "Avoid creating new tasks for service calls within a process"

- src/resources/uart_esp32.cc
For my next trick, I'll drop the ring buffer dependency.
> Fix UART breakage

- tools/gitversion.cmake
We were not incrementing the tag-version.
> Fix gitversion.

- src/linked.h
- src/resources/i2c_esp32.cc
- src/resources/i2s_esp32.cc
- src/resources/tcp_esp32.cc
- src/resources/udp_esp32.cc
These are changes to make newer compiler happy that we can already do now.
> Prepare for esp-idf 5.0

- tests/esp32/README.md
- tests/esp32/adc.toit
- tests/esp32/bad_i2c.toit
- tests/esp32/dac.toit
- tests/esp32/gpio_open_drain.toit
- tests/esp32/pulse_counter.toit
- tests/esp32/pulse_counter2.toit
- tests/esp32/pwm.toit
- tests/esp32/rmt_drain_pullup.toit
- tests/esp32/spi_keep_active.toit
- tests/esp32/touch.toit
- tests/esp32/uart_baud_rate.toit
- tests/esp32/uart_big_data_read.toit
- tests/esp32/uart_big_data_shared.toit
- tests/esp32/uart_big_data_write.toit
- tests/esp32/uart_flush.toit
- tests/esp32/wait_for1.toit
- tests/esp32/wait_for2.toit
With the current setup all tests can be run without needing to change any wirings.
> Unify the hardware tests

- lib/net/modules/dns.toit
Previously 1000ms, 1500ms, 2250ms   = 4750ms
Now 600ms, 900ms, 1350ms, 2025ms    = 4875ms
> Make the DNS more robust by trying 4 times.

- lib/pulse_counter.toit
- src/compiler/propagation/type_primitive_pcnt.cc
- src/primitive.h
- src/resources/pulse_counter_esp32.cc
- tests/esp32/pulse_counter2.toit
We forgot to register the unit in the resource group.
> Fix pulse counter.

- tools/kebabify.toit
Remove strange line in help text.
> Allow non-Toit files to be renames.

- .github/workflows/ci.yml
- README.md
- src/compiler/definite.cc
- tests/negative/gold/uninitialized-local3-test.gold
- tests/negative/uninitialized-local3-test.toit
> Fix definite-assignment test for super arguments

- src/resources/wifi_esp32.cc
> Add more WiFi logging.

- src/primitive_file_posix.cc
In a separate change we should rename primitive_file_posix.cc
> Readdir assumed it was not running on embedded

- lib/zlib.toit
- src/primitive_zlib.cc
- src/third_party/miniz/ChangeLog.md
- src/third_party/miniz/LICENSE
- src/third_party/miniz/examples/example1.c
- src/third_party/miniz/examples/example2.c
- src/third_party/miniz/examples/example3.c
- src/third_party/miniz/examples/example4.c
- src/third_party/miniz/examples/example5.c
- src/third_party/miniz/examples/example6.c
- src/third_party/miniz/miniz.c
- src/third_party/miniz/miniz.h
- src/third_party/miniz/readme.md
- src/top.h
- toolchains/idf/components/toit/Kconfig
This makes C language zlib available on all non-embedded platforms.
> Switch to miniz instead of zlib.

- .github/workflows/ci.yml
Works around https://github.com/actions/runner/issues/2788
> Use 'github.event.release.tag_name' instead of github.ref

- tests/package.lock
- tests/package.yaml
- tools/lsp/server/package.lock
- tools/lsp/server/package.yaml
- tools/lsp/server/project-uri.toit
- tools/toitlsp/lsp/project_uri.go
Also do a simple parent==dir check to stop traversing the parents.
> Use new fs package.

- src/os_win.cc
Use malloc to allocate the temporary buffer.
> Don't allocate 32K on the stack.

- lib/core/collections.toit
> Add more documentation to ByteArrays.

- .github/workflows/ci.yml
- Makefile
The 'install' only worked on Linux.
> Fix and test 'make install'

- src/compiler/compiler.cc
- src/compiler/lsp/completion.cc
- src/compiler/lsp/completion.h
- src/compiler/lsp/goto_definition.cc
- src/compiler/lsp/goto_definition.h
- src/compiler/lsp/lsp.h
- src/compiler/lsp/selection.h
Create the LSP selection handlers earlier and unify how they are called.
> Refactor LSP selection handlers

- tools/lsp/server/server.toit
- tools/toitlsp/go.mod
- tools/toitlsp/go.sum
- tools/toitlsp/lsp/compiler/compiler.go
- tools/toitlsp/lsp/compiler/parser.go
- tools/toitlsp/lsp/conn.go
- tools/toitlsp/lsp/doc_handlers.go
- tools/toitlsp/lsp/handlers.go
> Add a text-range to completions if the prefix ends with '-'

- src/heap.h
- src/interpreter.cc
- src/interpreter.h
- src/interpreter_run.cc
- src/objects.cc
- src/objects.h
- src/resources/tls.cc
- src/third_party/dartino/object_memory.h
- src/third_party/dartino/object_memory_copying.cc
- src/third_party/dartino/two_space_heap.h
The code generated by gcc for class_tag() == XXX was not great, with more shifts that needed.  Replaced this with has_class_tag(XXX) which is easier to
optimize.
> Faster float operations.

- lib/ble.toit
- src/resources/ble_esp32.cc
- tests/esp32/ble1-board1.toit
- tests/esp32/ble1-board2.toit
- tests/esp32/ble1-shared.toit
- tests/esp32/ble2.toit
Improves the shutdown if the BLE isn't shut down nicely from the Toit side.
> Improve BLE shutdown.

- Makefile
> Remove support for riscv64.

- lib/system/storage.toit
- tests/envelope/boot-flash-source.toit
- tests/storage-test.toit
Also deprecate `write --from` in favor of `write --at`.
> Allow io.Data for the storage lib.

- tools/firmware.toit
> Fix `firmware flash`.

- system/extensions/host/toit.run.toit
- tools/mirror.toit
- tools/system-message_.toit
- tools/system_message.toit
- tools/toit.toit
> Search for snapshot files when decoding system messages.

- lib/ble/ble.toit
- lib/ble/local.toit
- lib/ble/remote.toit
Fixes https://github.com/toitware/artemis-releases/issues/60.
> Let the manufacturer-data be a ByteArray.

- lib/ble/local.toit
- lib/ble/remote.toit
- src/event_sources/ble.h
- src/resources/ble_darwin.mm
- src/resources/ble_esp32.cc
> Fix BLE on macos.

- lib/ble/local.toit
- lib/ble/remote.toit
- src/event_sources/ble.h
- src/resources/ble_darwin.mm
- src/resources/ble_esp32.cc
> Fix BLE on macos. (#2513)

- lib/uart.toit
> Fix uart flush. (#2515)

- src/compiler/compiler.cc
- src/snapshot_bundle.cc
- src/snapshot_bundle.h
> Remove debug pipeline.

- .github/workflows/ci.yml
Depends on https://github.com/toitware/web-toitdocs/pull/280
> Update input-names and dispatch toitdocs-dev on commit to master.

- tools/toitdoc/serve.toit
The toitdoc code in the repository and the web-page were not in sync. -> Nothing worked.
> Update toitdoc html.

- tools/firmware.toit
The full-image is also working for wokwi and for flashing.
> Switch from "qemu" format to "full-image" format.

- tools/lsp/server/client.toit
- tools/lsp/server/file_server.toit
Together with https://github.com/toitlang/toit/pull/2583 fixes the LSP on Windows.
> Fix LSP on Windows.

- tests/minus_s/CMakeLists.txt
- tests/negative/CMakeLists.txt
- tests/tools/health.cmake
- tests/type_propagation/CMakeLists.txt
Fix warnings that appeared with cmake 3.31.0.
> Fix a few cmake warnings.

- lib/i2c.toit
> Fix bad 'i2c.write-reg' call.

- src/resources/spi_esp32.cc
- src/resources/spi_esp32.h
- src/top.h
> Use auto allocation of DMA channels for SPI.

- tests/fail.cmake
- tests/tls2-test.toit
The test was very flaky with microsoft.com.
> Use github.com instead of microsoft.com

- lib/esp32/net/ethernet.toit
Toitdoc doesn't support languages yet.
> Remove code-block language.

- tests/hw/esp32/README.md
- tests/hw/esp32/bme280-board1.toit
- tests/hw/esp32/bme280-board2.toit
- tests/hw/esp32/dht11-board1.toit
- tests/hw/esp32/dht11-board2.toit
- tests/hw/esp32/ds18b20-board1.toit
- tests/hw/esp32/ds18b20-board2.toit
- tests/hw/esp32/package.lock
- tests/hw/esp32/package.yaml
- DS18B20
- BME280 (I2C)
- DHT11
> Add more hw tests.

- tests/hw/esp-tester/mini-jag.toit
- tests/hw/esp-tester/shared.toit
- tests/hw/esp-tester/tester.toit
Also prefix each line with the name of the test-device.
> Prepare test devices in parallel.

- .github/workflows/ci.yml
The 20.04 worker isn't supported anymore.
> Update Ubuntu builders.

- lib/esp32/esp32.toit
- tests/hw/esp-tester/mini-jag.toit
More documentation and better naming.
> Improve esp32 constants.

- lib/i2c.toit
> Fix I2c registers.

- lib/rmt.toit
- tests/rmt-signals-test.toit
> Improve the RMT Signals class.

- .github/workflows/ci.yml
> Update AUR section.

- .github/workflows/ci.yml
- CMakeLists.txt
- Makefile
- README.md
- src/CMakeLists.txt
- src/compiler/CMakeLists.txt
- src/compiler/filesystem.cc
- src/compiler/filesystem.h
- tests/ctest/CMakeLists.txt
- toolchains/idf/components/toit/CMakeLists.txt
- tools/CMakeLists.txt
> Install Toit in standard locations.

- .github/workflows/ci.yml
- .github/workflows/tar-ball.yml
The vessels depend on the combine step.
> Move half of the AUR update back to CI.

- tests/hw/esp32/uart-rs485-board1.toit
- tests/hw/esp32/uart-rs485-board2.toit
The 1st board would finish the program and shut down the UART. However,
at that time there could have still been data in the buffers.
> Fix rs485 test.
